### PR TITLE
Rework of Hebrew vowels

### PR DESCRIPTION
**Pull request by cornelisbb**
This is a complete rework of Hebrew vowels/nikkuds/diakritics in de Serif fonts. This is done now. On my TODO list is to integrate the meteg into this, butt that is for later. All serif fonts now have proper vowel support. I have not done the sans fonts, because the Hebrew fonts there is the same as the serif.

I have also updated the fontlog with the details.

If this is accepted, I will fix the bugs on this that are reported.

The issues fixed with this PR are:
 #107 #486 #493 

I reference to the previous PR already in #340

### CODE REVIEW

**Comment by alerque** [comment]
Sorry this has taken so long to review, I got a bit distracted and then out of the groove of font dev stuff.

I'm trying to get out a new release now and would like to include this, but there are quite a few merge conflicts with other things I've accepted in the *master* branch. Most of them I know how to handle, but the change in encodings is confusing me when trying to get the I_J stuff for dutch merged because both branches have related changes and we need most of the I_J stuff from the master branch but the encoding changes from this one to make it all jive.

I'm not sure this will make the next release window, but I'm trying.

**Comment by cornelisbb** [comment]
Thanks for looking at it. I am not a git specialist, so sorry if I did something wrong. I know something about fontforge, feature files and Hebrew. I don't know how to help here, but if I can, I'll try. I can at least test the font and suggest corrections. Also for me, it has been long ago. :)

**Comment by alerque** [comment]
I'll try to handle the Git stuff, I *am* an expert at that side, more so than even fonts in general and certainly more than Hebrew.

Do you recall if there was a specific reason you switched some of the font faces from UnicodeFull to UnicodeBmp while working on the Hebrew vowel stuff?

**Comment by cornelisbb** [comment]
> Do you recall if there was a specific reason you switched some of the font faces from UnicodeFull to UnicodeBmp while working on the Hebrew vowel stuff?

No. As far as I've noticed this does not make a difference for Hebrew. Was probably by accident.

**Comment by alerque** [comment]
Yes as far as I know it mostly affects the way the FontForge interface treats the available character set. I'm going to try to change it back for the fonts it got set for, then re-normalize and try merging the stuff from main and see if that makes the overlap in changes more manageable.

**Comment by alerque** [comment]
Okay I think I got this...at least all of Git, FontForge, and FontShip are happy about the state of the source files. That does *not* mean the resulting state is correct because I had to do a lot of hand merging and I did it purely in the source using a text editor. In particular there were overlaps between this work and some other more minor fixes already in *master* and I hand merged them as best I could make sense of them.

Since I had to do this in a separate branch this is going to close as if GH things it didn't get merged, but it *should* all be in the current *master* in a moment. I'll post links to build artifacts here and if you can test that the Hebrew still works as expected I'll try to review the other changes and make sure they still work too.

**Comment by alerque** [comment]
So there has been some build trouble in CI land, but I think I have it all worked out now. When [this CI run completes](https://github.com/alerque/libertinus/actions/runs/10941247810) there should be artifacts attached to it with the current font builds. I'm stepping out for a bit, but the next thing to do (assuming they actually get posted) is to test those and make sure everything is working as expected given the changes submitted in this PR.

**Comment by alerque** [comment]
Somehow in merging this we lost one (Serif Regular) alternative plus signs from #504.

**Comment by alerque** [comment]
I got the plus sign from #502 back just by copying the `SplineSet` back where it belongs. It appears to have been the victim of some bad merging. I hope there are not many more instances like that.

Also I fixed CI so it doesn't choke on generating the preview any more. That was always a bad rule in this project, but *fixing* a bug in Fontship made it actually start trying to work in this project, and of course fail because we don't have XeLaTeX in CI.

Build artifacts with fonts for testing are finally working, latest ones as of this comment are [on this workflow](https://github.com/alerque/libertinus/actions/runs/10949198971).

**Comment by cornelisbb** [comment]
Thanks. Next week I have time to do some proper testing.

**Comment by alerque** [comment]
Just so you know, I kind of have ants in my pants to tag this. That may sound strange given I had the entire project on the back burner for years and it took me ages to get around to PR reviews and conflict management, but it looks like Libertinus Serif is going to get baked into the next major release of Typst (replacing the current Linux Libertine that it embeds). I'd really like to get a new tagged release out **and** have enough days left over that it gets some wider testing before Typst 0.12 drops just to make sure there aren't serious regressions.

I don't mean to push you at all (I know all about how volunteer time management goes!) but would you perhaps have a sample text in Hebrew that particularly exercises the bits you worked on here? I'd be happy to do some of the leg work of typesetting it in a before and after version and dropping a visual diff of some kind here.

As long as we're confident the current state is an improvement, I'd even rather release a v7.050 now and have to send out a v7.051 in a week with some tidbit we found rather than not having any of the last 2 years improvements land at all.

**Pull request closed without merging**
